### ISSUE TITLE
really shouldn't stomp on native namespace

### ISSUE THREAD

**Issue by bkardell** [jonathantneal/hfill#2]
Whether implemented this way or not, this is a custom element for now and should abide by rules of extension... Thus

```html
<x-h> or <contextual-heading> or <x-heading> 
```

or something seems considerably preferable to 

```html
<h>
```

**Comment by jonathantneal** [comment]
Done, now using `<x-h>` and the other names are suggested in https://github.com/jonathantneal/hfill#usage
